from collections.abc import Callable

from .h5d import DatasetID

__all__ = [
    "attach_scale",
    "detach_scale",
    "get_label",
    "get_num_scales",
    "get_scale_name",
    "is_attached",
    "is_scale",
    "iterate",
    "set_label",
    "set_scale",
]

def attach_scale(dset: DatasetID, dscale: DatasetID, idx: int) -> None: ...
def detach_scale(dset: DatasetID, dscale: DatasetID, idx: int) -> None: ...
def get_label(dset: DatasetID, idx: int) -> bytes: ...
def set_label(dset: DatasetID, idx: int, label: bytes) -> None: ...
def get_num_scales(dset: DatasetID, dim: int) -> int: ...
def get_scale_name(dscale: DatasetID) -> int: ...
def set_scale(dset: DatasetID, dimname: bytes = b"") -> None: ...
def is_attached(dset: DatasetID, dscale: DatasetID, idx: int) -> bool: ...
def is_scale(dset: DatasetID) -> bool: ...
def iterate[T](dset: DatasetID, dim: int, func: Callable[[bytes], T | None], startidx: int = 0) -> T: ...
