from typing import Final

from ._objects import ObjectID

CRT_ORDER_TRACKED: Final[int]

type _PropListID = (
    PropFCID | PropFAID | PropDCID | PropDXID | PropCopyID | PropLCID | PropLAID | PropGCID | PropDAID | PropOCID | PropTCID
)

class PropID(ObjectID): ...
class PropClassID(PropID): ...
class PropInstanceID(PropID): ...
class PropCreateID(PropInstanceID): ...
class PropCopyID(PropInstanceID): ...

# --- Object creation ---

class PropOCID(PropCreateID): ...
class PropDCID(PropOCID): ...
class PropFCID(PropOCID): ...

# --- Object access ---

class PropFAID(PropInstanceID): ...
class PropDXID(PropInstanceID): ...
class PropDAID(PropInstanceID): ...
class PropLCID(PropCreateID): ...
class PropLAID(PropInstanceID): ...
class PropGCID(PropOCID): ...

# --- Data type creation ---
class PropTCID(PropOCID): ...

def create(cls: PropClassID) -> _PropListID: ...
