__all__ = [
    "append",
    "get",
    "insert",
    "prepend",
    "remove",
    "replace",
    "size",
]

def append(search_path: bytes) -> None: ...
def prepend(search_path: bytes) -> None: ...
def replace(search_path: bytes, index: int) -> None: ...
def insert(search_path: bytes, index: int) -> None: ...
def remove(index: int) -> None: ...
def get(index: int) -> bytes: ...
def size() -> int: ...
