from h5py._objects import ObjectID
from h5py.h5s import SpaceID

class Reference: ...
class RegionReference(Reference): ...

def create(loc: ObjectID, name: str, ref_type: int, space: SpaceID | None = None) -> Reference: ...
def get_region(ref: Reference, id: ObjectID) -> SpaceID | None: ...
