from optype import numpy as onp

__all__ = ["check_numpy_read", "check_numpy_write"]

def check_numpy_read(arr: onp.AnyArray, space_id: int = ...) -> int: ...
def check_numpy_write(arr: onp.AnyArray, space_id: int = ...) -> int: ...
