from collections.abc import Iterator

from h5py._objects import ObjectID

from . import base
from .dataset import Dataset

__all__ = ["DimensionManager", "DimensionProxy"]

type _Name = str | bytes

class DimensionProxy(base.CommonStateObject):
    @property
    def label(self) -> str: ...
    @label.setter
    def label(self, val: _Name) -> None: ...
    def __init__(self, id_: ObjectID, dimension: int) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __getitem__(self, item: int | _Name) -> Dataset: ...
    def attach_scale(self, dset: Dataset) -> None: ...
    def detach_scale(self, dset: Dataset) -> None: ...
    def items(self) -> list[tuple[str, Dataset]]: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[Dataset]: ...

class DimensionManager(base.CommonStateObject):
    def __init__(self, parent: ObjectID) -> None: ...
    def __getitem__(self, index: int) -> DimensionProxy: ...
    def __iter__(self) -> Iterator[DimensionProxy]: ...
    def create_scale(self, dset: Dataset, name: str = ...) -> None: ...
