from collections.abc import Iterator, Mapping
from typing import Final, Literal, overload, override

__all__ = ["FilterRefBase", "Gzip", "decode", "encode"]

decode: Final[tuple[str, ...]] = ...
encode: Final[tuple[str, ...]] = ...

_COMP_FILTERS: Final[dict[str, int]] = ...
_FILL_TIME_ENUM: Final[dict[str, int]] = ...
DEFAULT_GZIP: Final[int] = ...
DEFAULT_SZIP: Final[tuple[str, int]] = ...
CHUNK_BASE: Final[int] = ...
CHUNK_MIN: Final[int] = ...
CHUNK_MAX: Final[int] = ...

class FilterRefBase(Mapping[str, object]):
    filter_id: int = ...
    filter_options: tuple[int, ...] = ...
    @override
    def __len__(self) -> int: ...
    @override
    def __iter__(self) -> Iterator[str]: ...
    @override
    @overload
    def __getitem__(self, item: Literal["compression"]) -> int: ...
    @overload
    def __getitem__(self, item: Literal["compression_opts"]) -> tuple[object, ...]: ...
    @overload
    def __getitem__(self, item: str) -> object: ...

class Gzip(FilterRefBase):
    def __init__(self, level: int = ...) -> None: ...
